name = "ScalarWave1D"
uuid = "63f509d8-7292-40c2-93d0-f8cf0b8ff1ec"
authors = ["Stamatis Vretinaris"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
